### ISSUE TITLE
Contributor credit?

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#140]
At the moment the book has a single set of authors. For 3rd-party contributions it might be important to document authorship in a more detailed fashion. Maybe a statement underneath the chapter title would work?

That being said, I would very much prefer to have the whole book being a single editable, evolving entity and not a collection of contributed chapters, where we would have to contact original authors to edit their contributions.

ATM we link the 'contributor list' on the frontpage to https://github.com/datalad-handbook/book/graphs/contributors While this is technically precise, it focuses on the commit of a contribution. But in reality such a contribution could have been the result of debate and evaluation of multiple people.

A dedicated hand-written 'contributors' section could be a solution to both issues: declare original authorship when desired, and acknowledge non-commit contributions.

I have no good idea on how to structure/order such a page. I would like to avoid having to "weigh" contributions in order to determine a subjective importance. The only other two orders I can think of are alphabetical and 'order of appearance' -- and I Iike the latter more.

What do you think?

**Comment by adswa** [comment]
I agree with what you say. It would be good to acknowledge every kind of contribution. @marisaheckner for example already contributed with helpful remarks and discussions in private, and I would like her to show up somewhere as a contributor.
As the book is developed here, I like acknowledging contributions somewhere in this repository instead of in the book (but linking whereever we mention contributors into the book as it is currently done with the graph). In my opinion, having a large chunk of contributors mentioned is better than attaching a name to any single section/page -- it makes the whole book look like more of a group effort and might be more inviting (both because we don't attach a name and maybe responsibility to any part, and also because this makes every contribution as simple as it may be equally valuable). 
I'm also in favor of a "order of appearance" order.

There is https://allcontributors.org/ and they have a bot who automatically generates a [Contributors](https://github.com/all-contributors/all-contributors#emoji-key) section in the README of the project (in order of appearance), and it seems as this would make it easy to establish a workflow in which we can instruct the bot or use the client to add a contributor after someone made an issue or a pull request, for example. It allows to "group" the contributions using emoji keys (for example "bug", "question", "content", "example", ... [all are listed here](https://allcontributors.org/docs/en/emoji-key)) The downside to this is that from what it looks like it can only add people that have a Github handle.

Alternatively, we could add  contributors (and ask them to add themselves) to something like a ``zenodo.json`` or ``CONTRIBUTORS`` file. This allows adding anyone, even if they are not on Github, but is not as visible.

**Comment by mih** [comment]
Uhh, great find! I am very much in favor of doing that -- in fact, all of it. `zenodo.json` will have have to come anyway at some point, and a custom `CONTRIBUTORS` could be specifically declared as an extension to the generated list (I'd like to avoid forcing people to join GitHub).

**Comment by adswa** [comment]
Tbh, I only know of allcontributors because @KirstieJane uses it, credit goes to her project for being a great role model. :)
I'll take care of doing all of that, thx for the suggestion and discussion!

**Comment by adswa** [comment]
Let's try this:

@all-contributors please add @loj for ideas maintenance review talk question content

**Comment by KirstieJane** [comment]
Love that you’re using All contributors! One quick warning - you can get into a terrifying merge conflict nightmare if you have multiple PRs from the bot open at the same time. The best work flow is open & merge, then open & merge. Easy when you’re adding contributors going forwards, more of a problem when you’re adding folks to the table in a batch

(Brought to you by some lost hours of confusion on the Turing Way 😉).

**Comment by mih** [comment]
Looks and works great! Thx much @adswa and thanks @KirstieJane for the warning.

**Comment by adswa** [comment]
Thanks for that warning @KirstieJane! That has come just in time!

**Comment by adswa** [comment]
(sorry, accidentally closed on my phone - will shortly close properly with the other missing files)

**Comment by mih** [comment]
I think this is done now, right? If not, please reopen.

**Comment by adswa** [comment]
All done, thx
