### ISSUE TITLE
What and where of metadata

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#17]
Recording an aspect that came up in an exchange with @adswa 

Datasets are full of metadata, and there are two essential types

1. (history of) dataset content identity and availability information (i.e. the Git repo)
2. extracted metadata that is managed by datalad itself as (somewhat hidden) dataset-internal content

The big difference is that (1) is only available after a repository is locally available, while (2) can come with any superdataset. Additionally, both types cover different aspects: (1) metadata geared towards transport and versioning logistics, (2) focused on the semantics/meaning of the managed data. Although recent work in https://github.com/datalad/datalad-metalad aims to blur this boundary and tries to enable a more comprehensive dataset description 

We should be clear on what is referred to by "metadata", but proper terms have not been established yet.

**Comment by adswa** [comment]
Because somewhat related I'm adding this to this issue:

I have started to work on a chapter on DataLad's metadata capabilities. This is tricky, because of ongoing datalad-metalad development, https://www.datalad.org/for/data-discovery being quite outdated API-wise, and me not knowing which command (of either datalad/metadata or datalad-metalad) is sensible to include. However, in general I think it is useful to have a section on metadata at this stage, because it 1) will be helpful when interacting with HBP people or others interested in metadata, and 2) get me closer to an in-depth understanding of metadata handling in DataLad. However, this section at this point can't yet live up to being a full, in-depth description/tutorial on all things metadata, and rather showcasing/demonstrating core principles and some examples.

My current take is the following (please chime in on what you find sensible or not):

- demonstrate one aspect of metadata and making use of metadata by demonstrating ``datalad search`` similar as in https://www.datalad.org/for/data-discovery for data discovery in the DataLad superdataset ``///``. TODO: I will yet need to look a bit into the different modes and how elaborate a search could become. 
- explain the concept of an extractor, and show a behind-the-scenes of the metadata extraction in the longnow dataset. For this, I assume an intro to datalad-metalads commands will be necessary.
- Outline some perks of using DataLad for metadata: automatic extraction, domain-agnostic & extensible extractors, compatibility to Googles dataset search... 

If you have thoughts on what might be relevant or irrelevant I'm eager to know.

**Comment by adswa** [comment]
This issue can be closed as well IMO. We're aware of the distinction of file-availability-metadata and metadata-metadata, and the handbook is in a state in which readers can easily make this distinction if they have read the handbook's Basic section. As for the topic of a metadata chapter, a new issue or thoughts in the existing draft PR are more appropriate locations.
