### ISSUE TITLE
not bother with --description for create

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#190]
docs/basics/101-101-create.rst mentions `--description` and promises audience to thank authors later for advising to use it.  I would argue that in reality any custom human provided description is inferior to the default `host:path`, since at best it provides only a hint about actual location, while `host:path` provides a descriptive and often "ready to use" information (just cut/paste and use it as an ssh remote if was not moved). My opinion of its superficial utility supported by the fact that  throughout examples in the book it is rarely used or relied upon:

```shell
$> git grep -e '[^\[]--description' | grep -v _examples
basics/101-101-create.rst:of your dataset with the *optional* ``--description`` flag. (At the moment,
basics/101-101-create.rst:   $ datalad create --description "course on DataLad-101 on my private Laptop" -c text2git DataLad-101
basics/101-107-summary.rst:    datalad create --description "here is a description" -c text2git PATH
basics/101-116-sharelocal.rst:   $ datalad install --source ../DataLad-101 --description "DataLad-101 in mock_user"
basics/101-116-sharelocal.rst:  datalad install --source ../DataLad-101 -r --description "DataLad-101 in mock_user"
basics/101-116-sharelocal.rst:  datalad install -s ../DataLad-101 --description "DataLad-101 in mock_user" -r --recursion-limit 1
basics/101-120-summary.rst:  ``--description`` provided during a :command:`datalad create`. It is a very
usecases/collaborative_data_management.rst:   $ datalad create -c yoda --description "my 1st phd project on work computer" myanalysis
```

so I wondered
- why bother and shouldn't it better to not mention it in the book?
- if authors use/rely on it in their day to day use of datalad (I personally don't)?

PS I also now tuned an [issue for perspective datalad mv](https://github.com/datalad/datalad/issues/1193#ref-pullrequest-468547905) to adjust dataset description in case it is in `host:path` form

**Comment by adswa** [comment]
As for "why": initially, because I found this in the datalad docs in the "collaborative workflow" example. Personally, I also don't use it, but I found it quite cool in conjunction with ``git annex whereis``. I don't have any strong feelings about this, I'd be fine with e.g. turning information on ``--description`` into a ``findoutmore`` in the first section or a later section on ``git annex whereis``. However, thinking about it (also with the issue you raised in #189), with the current status quo of my machine being the one the books examples are primarily build on, the description spares me to explain any personal ``host:path`` that would be different for every user, and instead adds a description that is the same for everyone who executes it...

@mih, do you have any opinion on ``--description``?

**Comment by yarikoptic** [comment]
Good point on the consistency effect for the book! Placing it into findoutmore and describing that you use it in the book for the purpose you described would IMHO be the best - it will be a factual example where it is actually useful ;-) 
But also it's might be worth checking if HOSTNAME variable is consulted by git annex for the description, may be then build could just set it. Then book builds will be consistent and descriptions descriptive and similar to what audience would see in the real life

**Comment by yarikoptic** [comment]
BTW, just a note, yesterday I thought about a use case where use of `--description` would be really needed.
Whenever we ENH to upload datasets tarballs to figshare et all alongside with their `.git` so they could be properly `clone`/`install`ed from those resources.  I envision implementation where we would first create a local throw away clone (to get a nice clean `.git`), and for that one we better provide description which would reflect the target location (e.g., url on figshare).
