### ISSUE TITLE
Zenodo.json needs contributor information

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#220]
Currently, the all-contributors bot takes care of acknowledging contributors in the ``README`` and the authorlist of the PDF, but the ``zenodo.json`` file is not maintained yet. We should think of a way to automate this, or ask all current contributors to add themselves for a start.

**Comment by mih** [comment]
Automation would be great.

**Comment by effigies** [comment]
Possibly useful starting points:

* Adds all contributors, and reorders based on number of git commits: https://github.com/nipy/nibabel/blob/master/tools/prep_zenodo.py
* Does not add new contributors, reorders based on number of lines you can `git blame` on them, uses fuzzy name matching: https://github.com/nipy/nipype/blob/master/tools/update_zenodo.py
* Similar to nibabel's, but allows blacklisting contributors who don't want to be listed, including commits to another repository, and counting contributions after an initial commit: https://github.com/bids-standard/pybids/blob/master/tools/prep_zenodo.py

All are based on `git` history. I don't know of an example that takes another source, but `.all-contributorsrc` looks nicely structured. If you're using git history, keeping the mailmap synced makes life a lot easier.

These preserve any additional fields like ORCID when matched, so I tend to just ask users to add their info when committing changes to the `.zenodo.json`. They also will treat "First Last" the same as "Last, First", but won't change the order (difficult to do generally when you have last names like "von der Malsburg" or "di Oleggio Castello"), so that needs to be done manually.

**Comment by adswa** [comment]
Thanks for these pointers, @effigies! I will look into the ``.zenodo`` issue again when there are fewer pressing content-related TODOs, but I'm certain they'll be useful!
