### ISSUE TITLE
cheatsheet mismatch between website and github

### ISSUE THREAD

**Issue by AlexandreHutton** [datalad-handbook/book#360]
The cheatsheet .svg on the [website](http://handbook.datalad.org/en/latest/basics/101-136-cheatsheet.html) has misaligned titles and blank sections (top-right), but the version on GitHub .pdf doesn't. It looks like the src on the website just needs to be updated to the GitHub version.

**Comment by adswa** [comment]
thanks for the bug report! My guess is that this due to the fact that the figure we used as a "preview" of the PDF in the handbook is an .svg with text blocks. I have made changes to the artwork submodule to render a dedicated "preview" .svg which has its texts converted to path objects (this way, it is not browser dependent how fonts are rendered), and coming in #361 I'm referencing this updated preview.

@all-contributors please add @AlexandreHutton for bug.
