### ISSUE TITLE
404 page for non-book-root pages are visually broken

### ISSUE THREAD

**Issue by aqw** [datalad-handbook/book#426]
**What does not work?**

The 404 page for resources that are not in the top-level of the book are visually broken. For example:

* beautiful: http://handbook.datalad.org/en/latest/nope
* pain all over my broken face:
  - http://handbook.datalad.org/en/latest/nope/nope
  - http://handbook.datalad.org/en/nope
  - http://handbook.datalad.org/nope

**Background information**
Please provide us with everything relevant to make sense of the issue such as:
1. Your operating system

Windows for Workgroups 3.1

Also doesn't work on my TempleOS box.

2. Your version of DataLad and git-annex. Consider providing the output of a ``datalad wtf``.

DataLad 0.3.1 (I learned long ago that the version of the software I run needs to match the version of my OS in order to be compatible).

Will provide the output of ``datalad wtf`` by post, once my dot matrix printer is done building a tower of fanfold paper on the floor.

3. Your browser [e.g., chrome, safari] and its version [e.g., 22]

Netscape Communicator 4.08.

4. Drinks:

Mimosa

**Screenshots/Trace backs**

Shooting my CRT feels like a disproportionate response for such a minor bug; the existing holes are difficult enough to read around. I will instead choose the option to draw on the rear with my acrylics set, and will send the monitor by post if requested.

**Additional context**

Extended home office and social isolation.

**Comment by adswa** [comment]
LOL. This was so funny that it got me out of bed. And, mind you, I was naked in bed with a coffee - this is a position I rarely /ever/ leave.* 

Thanks for the bug report. Its so sad that our beautiful 404 page isn't rendered... it has custom artwork...
I googled around, and was astonished to find a [custom sphinx 404 page extension](https://sphinx-notfound-page.readthedocs.io/en/latest/):

> Sphinx does not create a 404 page by default. Although, you can create it by adding a simple 404.rst file to your docs but…

>  If you are reading this documentation, you may already experienced the problem that all your images do no load, all your styles are broken and all the javascript events does not work, when accessing the 404 page of your documentation.

> So, if you want to have a nice custom 404 page, you will probably want to use this extension to avoid this headache and let the extension handle these URLs properly for you.

I'll make sure we have a proper "Get lost, there is nothing to be seen" - 404 page**. Many thanks!


*What may have contributed to me leaving is that my bed is now [drenched with coffee. Because I laughed so much.](https://tenor.com/view/spits-coffee-laughing-lol-lmao-happy-gif-15401789)

** After a coffee and putting on new sheets

**Comment by aqw** [comment]
I'm sorry to have caused you to abandon the comfort of your morning routine. ;-)

The quote you provided from their docs is hilarious. I respect the directness:
> If you are reading this documentation, you may already experienced the problem that all your images do no load, all your styles are broken and all the javascript events does not work, when accessing the 404 page of your documentation.

**Comment by adswa** [comment]
Fixed by #428 - thanks!
@all-contributors add @aqw for bug, ideas

**Comment by adswa** [comment]
This was fixed with #428, and we have a beautiful 404 page now: http://handbook.datalad.org/en/latest/nada

**Comment by aqw** [comment]
Awwww yisss. :-D
