### ISSUE TITLE
Make chapters/sections "permanlinked" and/or redirected to a new location

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#439]
More external resources starting to point to the handbook chapters/sections.  It would be a good service to those external resources to make desired content (chapters or sections) within handbook reachable, pointing to the most recent (released) version so people could always discover what is the current state of things on a specific subject (installation, adding external resources, etc).

Handbook is under active development, things change, chapters and sections rename, fragment ids (the id after `#` in the url pointing to content within pages) change. Even though nothing could be done about fragments (but those are not that important unless page is way too long), it should be possible to

- make chapters and sections files be named not using their index in TOC, which can change (like in bd677908dbf6793b0123da33988d28ff2c57b494), but use some identifier (as their already have in sphinx on top of the file) so produced pages names have better chance to be more permanent and not being renamed if a new interim chapter or section is introduced.

- identify which pages disappeared by looking at web access logs, or may be via some other "catch all" 404 handling page (`ErrorDocument` setting in apache, didn't check if github pages provide support), and then establish redirects where needed.

**Comment by mih** [comment]
FTR: Here is the entrypoint to all the discussion we had about this https://github.com/datalad/datalad/issues/4034

**Comment by adswa** [comment]
Its good to have the discussion, thanks for the issue. It definitely would be cool to come up with some set of rules that formalize additions of new chapters or reference handles in a way that makes them as
robust as possible for linking. In datalad/datalad#4034 we already debated how to establish "caveman" navigation, and atm this led to the "Symbols" entry in the [handbook index](http://handbook.datalad.org/en/latest/genindex.html). Those numerical codes attempt to follow a manpage-like classification with separate, "robustified" references. It is detailed [in the Contributing file](http://handbook.datalad.org/en/latest/contributing.html#intersphinx-mapping):


> The handbook tries to provide stable references to commands, concepts, and use cases for Intersphinx Mappings. This can help to robust-ify links – instead of long URLs that are dependent on file or section titles, or references to numbered sections (both can break easily), intersphinx references are meant to stick to contents and reliably point to it via a mapping in the index under Symbols. An example intersphinx mapping is done in DataLad.

> The references take the following shape: .. _1-001:

> The leading integer indicates the category of reference:

> 1: Command references
> 2: Concept references
> 3: Usecase references

> The later integers are consecutively numbered in order of creation. If you want to create a new reference, just create a reference one integer higher than the previously highest. The currently existing intersphinx references are:

>    1-001: DataLad cheat sheet
>    1-002: II - DataLad, Run!
>    2-001: YODA: Best practices for data analyses in a dataset
>    2-002: Data integrity
>    2-003: DataLad’s result hooks
>    3-001: Building a scalable data storage for scientific computing


I think I don't know what you exactly mean by your bullet points (that may be because my neighbors above are doing something that sounds like aa stampede to the music of oriental markets)


>    make chapters and sections files be named not using their index in TOC, which can change (like in bd67790), but use some identifier (as their already have in sphinx on top of the file) so produced pages names have better chance to be more permanent and not being renamed if a new interim chapter or section is introduced.

You refer to the chapter files that contain sublevel toctrees, correct? I.e., ``basics1roc.rst`` and so forth? Yes - very true, I'll replace the integers with strings. Does this comment also refer to any section files (i.e., any of the files that follow the ``101-<int>-<desc>`` format?

>    identify which pages disappeared by looking at web access logs, or may be via some other "catch all" 404 handling page (ErrorDocument setting in apache, didn't check if github pages provide support), and then establish redirects where needed.

I have a rough idea what you are talking about, and it sounds like a nice thing to have, but I didn't find anything about this for readthedocs yet (googled only briefly, but I'm not sure I know the vocabulary for really effective searches for that). I'll keep looking, but if you are faster and find something that can do this for readthedocs, please let me know.

**Comment by adswa** [comment]
I think a number of PRs and issues have at least started to address this.
#457 introduced a change to the naming convention of chapter toctrees: Instead of by order in the book, they are now identified with a content description. If you were to refer to the Chapter on DataLad datasets, you could now link http://handbook.datalad.org/en/latest/basics/basics-datasets.html instead of http://handbook.datalad.org/en/latest/basics/basics-1.html. This is not bulletproof, but much closer to it. I see very little reason in changing overall chapter topics, and this link will resolve regardless of chapter order.
Since we started the handbook, the individual sections had integer+topic labeling, e.g., http://handbook.datalad.org/en/latest/basics/101-106-nesting.html. Especially for the Basics, it is not likely that these file names change. The consecutive execution of code snippets in the handbook relies on these naming schemes, and the Basic's narrative is already in a quite stable state. Individual sections can thus also be very likely persistently linked.
My thought in #444 provide a rough way to link to precise major handbook releases. (``en/latest/``, ``en/stable/``, or ``en/<version>`` into the URL. And there is also the scheme that @mih and I have come up with and described in #377 for intersphinx references.

The only exceptions are things like #484. In my opinion, they should be limited, only done if it is unlikely that they have been referenced elsewhere under their old link, and they should be done as early as possible.

Given all of this, I would suggest to close this issue and look at individual problems should they arise. Please reopen if you disagree.
