### ISSUE TITLE
introduce `datalad drop` early

### ISSUE THREAD

**Issue by pvavra** [datalad-handbook/book#460]
When reading the section "4.1 Dataset content identity and availability information", I was expecting to see something about `datalad drop` there. Specifically, the narrative was setting up how efficient it is to not download everything at once.

In that vein, it would be fitting to introduce a way how to "remove" local copies of tracked files to free up disk-space again. For example, say that after listening to a podcast, you can `drop` it again. This would nicely support the point that provenance is useful.

I think that a full discussion of the git vs git-annex stuff should wait for later (i.e. as it is done now) and a link to that discussion should be included in Chapter 4. Still, such an early hint at "additional benefits" is a good motivator for picking up datalad, I think ;)

**Comment by adswa** [comment]
Thanks for your thoughts @pvavra. I agree that ``drop`` should be introduced earlier, and this is a good place to do so (I believe the earliest it is introduced is the section on file system operations). If you feel like doing a PR, please go ahead, else I see to it in the next few days.

Note to self: I need to check whether there is a way to display chapter numbers  in addition to section numbers, or somehow introduce the chapter/section distinction. I initially thought you were referring to [chapter 4, section 1](http://handbook.datalad.org/en/latest/basics/101-116-sharelocal.html) (Collaboration), instead of [chapter 1, section 4](http://handbook.datalad.org/en/latest/basics/101-105-install.html#dataset-content-identity-and-availability-information).
