### ISSUE TITLE
Clickable sheetsheet in .html version?

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#582]
I  really liked https://www.openscad.org/cheatsheet/ ;-) and found that PDF version of cheat sheet already has all the links! awesome!  but http://handbook.datalad.org/en/latest/basics/101-136-cheatsheet.html has only a "static png".  I wonder if sphinx could just embed svg instead png and then may be it would just all work since http://www.onerussian.com/tmp/datalad-cheatsheet_p1.svg itself is already working nicely ;)

**Comment by adswa** [comment]
>  and found that PDF version of cheat sheet already has all the links! awesome!

Yes! I was so proud when we achieved that, its a really elaborate setup ;-) [We had to distribute a go library with the artwork repo to make it work](https://github.com/datalad-handbook/artwork/blob/master/Makefile).

>  I wonder if sphinx could just embed svg instead png

Yes, it would, but it frequently broke the build process because the svg was so large that mine and @mih's versions of ``librsvg2-bin`` went into strike during building :/ We had to change (initially to PDF, later to png based on Alex advice) in e97d230913. But since a click on the png triggers a download of the clickable PDF, users are just one extra click away from the linked docs.

**Comment by adswa** [comment]
Unless we redo the cheatsheet in smaller chunks this wouldn't work due to rendering errors already (no idea actually whether the PDF in Sphinx would stay clickable in the HTML). User get to have a clickable cheatsheet once they downloaded it, though. Therefore, I'm closing this.
