### ISSUE TITLE
permissions issues in basics 1.3 appending to notes

### ISSUE THREAD

**Issue by petralenzini** [datalad-handbook/book#586]
Is there a slack channel for basic questions like this?  Don't think this qualifies as an 'issue' but I can't figure out what to google to get around this permissions issue which is preventing me from adding to my own notes.  
![image](https://user-images.githubusercontent.com/24570185/95088030-07ebb800-06e8-11eb-85b3-d83b7a557c3d.png)

Would love to be able to support this effort someday.

**Comment by adswa** [comment]
Hi @petralenzini! What I think you are seeing is the following:

For some reason, ``notes.txt`` was annexed (chapter 3 of the Basics has more insights into this). This shouldn't happen if you follow all the code snippets in the Basics. I assume because the dataset you created was created without any configuration, with a plain ``datalad create``. Its easy to fix, but I'd like to make sure that there is nothing broken in the handbook that leads to this, so I would really appreciate a contribution of yours in form of helping me figure out how you got into to situation that you are in now :)

Let's start with the following:
To see if my assumption is correct, could you tell me 
- did you create the dataset using ``datalad create -c text2git <nameofyourdataset>``, or did you just use ``datalad create <nameofyourdataset>``?
- If you did use a configuration: what's inside the ``.gitattributes`` file in the dataset? (``cat .gitattributes``)

Background information on whats happening (if my assumption is correct):
By default, contents in a dataset get handled by git-annex. The mechanism and reason for this is detailed in [chapter 3](http://handbook.datalad.org/en/latest/basics/basics-annex.html). Anything that is annexed is write-protected to ensure file integrity. To be able to modify an annexed file, you can either
- unlock it (using ``datalad unlock notes.txt``) whenever you want to do a modification
- store it in Git (which would be done with the ``-c text2git`` configuration of ``datalad create``

Its much more convenient to work with text files if they are stored in Git, so configurations such as ``text2git`` or ``yoda`` (later in the handbook) are useful, because they provide the right configurations without effort for the user. Sections [5.2](http://handbook.datalad.org/en/latest/basics/101-123-config2.html) and [5.3](http://handbook.datalad.org/en/latest/basics/101-124-procedures.html) have examples and explanations on how these configurations work and how to set them.

## Here's how to fix it (given my assumption is correct):

```
git-annex unannex notes.txt
datalad run-procedure cfg_text2git
datalad save
```

Happy to give you more background info if you want, but first let's see if this fixes it for you.

**Comment by adswa** [comment]
> Is there a slack channel for basic questions like this? Don't think this qualifies as an 'issue' but I can't figure out what to google to get around this permissions issue which is preventing me from adding to my own notes.

GitHub issues are fine, but we also have a Matrix channel: https://app.element.io/#/room/#datalad:matrix.org

**Comment by petralenzini** [comment]
Shoot, you're right.  My history says I definitely just initiated the dataset with 'datalad create.'   
Your solution fixed the problem.  I look forward to learning more, and will start listening to the Matrix channel. 

Petra

**Comment by adswa** [comment]
Glad it helped - I'll close this issue :)
