### ISSUE TITLE
Minor typo and other feedback on the INM7 version

### ISSUE THREAD

**Issue by jadecci** [datalad-handbook/book#593]
Dear DataLad team, thanks for the wonderful book! Apologies if I'm not following the format for issues properly. I would like to provide some minor feedback after following through the INM7 version of the handbook.

First, I found 2 typos:
1. In Chapter 3.2 first paragraph, `list_files.py` should have been `list_titles.sh` (which was created in chapter 2.1 and 2.2 I believe)
2, In Advanced Chapter  2.2 first paragraph, `you are not population datasets` should be `you are not populating datasets`

There are 2 other issues I ran into when implementing code from the handbook:
1. In the `Find out more` block in Chapter 3.2, `md5sum` was used for getting the checksum. It might be worth mentioning that, on MacOS, this command should be `md5` instead.
2. In Chapter 7.2, the `datalad container` extension was used. However, there was no explicit mention that this extension need to be installed manually before use.

Thanks again for the handbook :) Please let me know if it would make things easier for me to submit a pull request.

**Comment by adswa** [comment]
Thanks a lot for finding and reporting those issues!

hey @all-contributors please add @jadecci for bug

>  Please let me know if it would make things easier for me to submit a pull request.

Since you are asking, we would definitely appreciate a PR a lot. If you're up for it, please give it a go :) Let me know if that's ok and if there is something I can help you with (if interested/relevant there is some general information on how the book works [here](http://handbook.datalad.org/en/latest/contributing.html)). Please also feel free to add yourself to the `zenodo.json` file (just add that as a commit to the PR) -- this makes you a coauthor on https://zenodo.org/record/3608612#.X5AWtiWxUUE

**Comment by adswa** [comment]
@all-contributors please add @jadecci for bug

**Comment by adswa** [comment]
This was closed with @jadecci 's PR - closing the issue.
