### ISSUE TITLE
windows installation instructions are "suboptimal"

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/book#598]
http://handbook.datalad.org/en/latest/intro/installation.html#windows-10

 `pip install datalad~=0.12`

that iirc would install 0.12 (unmaintained) series.  Why not just `conda install -c conda-forge datalad` ?

**Comment by adswa** [comment]
Yes, absolutely. That's why I'm fixing them in #588 ;-)
From my POV, this PR can be merged whenever we're confident that those instructions are an improvement to before. IIRC, there were still a handful of git-annex test failures afterwards, though...
https://github.com/datalad-handbook/book/pull/588/files#diff-224f62b9c50417d3b748329006f2428278d00a188771339117833242489f90cd

**Comment by adswa** [comment]
I will close this, it was fixed in #588.
