### ISSUE TITLE
Mistyped AWS credentials when downloading HCP data

### ISSUE THREAD

**Issue by josephmje** [datalad-handbook/book#620]
**Is your feature request related to a problem? Please describe.**
I was following the [datalad handbook instructions](http://handbook.datalad.org/en/latest/usecases/HCP_dataset.html) for downloading the HCP data. However, I accidentally misentered my AWS secret key and failed to download any of the subjects using `datalad get`. I tried to find the `.aws` folder that would contain my AWS keys but then realized that datalad uses the system keychain to save this info.

**Describe the solution you'd like**
I managed to find a way to edit my AWS keys using the `keyring` package in Python. The solution is below. I was wondering whether this solution would be wanted somewhere in the datalad handbook?

```python
import keyring

keyring.set_password("datalad-hcp-s3", "key_id", <password>)
keyring.set_password("datalad-hcp-s3", "secret_id", <password>)
```

**Comment by adswa** [comment]
Thanks @josephmje!
Resetting credentials (should DataLad not prompt you automatically upon an unsuccessful authentication during ``get``) is not only a hassle, its also severely underdocumented. We have been putting it off because we try to shift to the Git Credential Manager (which would allow a cross-plattform compatible standard solution), but so far, nothing has come out of these efforts.
Adding information on how to do this would be great, and your solution also seems to be applicable to plenty of systems.*

Would you like to add this piece of information as a ``Findoutmore`` to the [file you referenced](https://github.com/datalad-handbook/book/blob/master/docs/usecases/HCP_dataset.rst), maybe in the section about "Data retrieval"?

In rst, the correct markup would take the following form:

```RST
.. findoutmore:: Resetting AWS credentials via Python's keyring package (Or any other title)

   Some text ...

   .. code-block:: python 

      import keyring

      keyring.set_password("datalad-hcp-s3", "key_id", <password>)
      keyring.set_password("datalad-hcp-s3", "secret_id", <password>)
```

Let me know if you to do a PR :) In any case, let me add your contribution to the front page.

hey @all-contributors please add @josephmje for ideas

If you do a PR, please also feel free to add yourself to the [.zenodo.json](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) file as outlined in the [Contributing Guidelines](http://handbook.datalad.org/en/latest/contributing.html#acknowledging-contributors), or, if you don't do a PR, let me know if I should add you.

I'll also make sure to restart the conversation about credential management in the next dev call.

\* (Other alternatives include: a) Locating ``keyring_pass.cfg`` on your system and removing the encrypted password to retrigger credential setup, but while this file lies in ``~/.local/share/python_keyring/`` for many systems, I've failed to find it on other peoples computers reliably many times, and on Windows it doesn't exist at all (but there is a credential manager GUI); b) setting the corresponding environment variables ``DATALAD_hcp_s3_key_id`` and ``DATALAD_hcp_s3_secret_id``, but that's a plain text password in a ``.*shrc`` file)

**Comment by adswa** [comment]
FFS. I hate the bot. 
hey @all-contributors please add @josephmje for ideas
