### ISSUE TITLE
Instructions for "Old" openneuro dataset derivatives

### ISSUE THREAD

**Issue by Remi-Gau** [datalad-handbook/book#687]
For a tutorial I came across (see [here](https://nilearn.github.io/auto_examples/04_glm_first_level/plot_bids_features.html#id1)) an openneuro data set that has its derivatives on the old openfMRI set up.

> The preprocessed data described in are available at https://legacy.openfmri.org/dataset/ds000030/ and via Amazon Web Services S3 protocol at: s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/derivatives/

Is it worth updating openeuro age of handbook ? http://handbook.datalad.org/en/latest/usecases/openneuro.html

That could be an edge case though.

But it could be an opening to explain how deal with S3 buckets... That I know nothing about though they are mentioned in the HCP page: http://handbook.datalad.org/en/latest/usecases/HCP_dataset.html?highlight=aws#the-datalad-approach

**Comment by adswa** [comment]
Sorry, I only saw this issue now. Maybe its the lack of coffee but I am only 72% sure if I understand your issue correctly...

The easiest way to get legacy datasets from openfmri is via 

```
datalad clone ///openfmri/ds000030
```

Other datasets on there follow the same pattern - I'll add it to the openneuro page, thanks!

> But it could be an opening to explain how deal with S3 buckets... 

I *think* your question goes a bit into the direction of how to clone from an S3 bucket?
If it is, that's not really possible, because  we only use s3 buckets as just another cloud service for storing large data. When generating datasets from data that lives in s3 buckets we use ``datalad addurls`` to take all of the S3 urls and build a dataset from them. Do you want to have a stand-alone section on this? :)
