### ISSUE TITLE
[BUG] OpenNeuro / Github discrepancy

### ISSUE THREAD

**Issue by kingjr** [datalad-handbook/book#864]
### Current behavior

I am not sure this is the right place to raise this issue.

I have difficulties downloading data from the OpenNeuro plaftorm. There seems to be a mismatch between the data on the this platform and the corresponding dataset(s) on github/OpenNeuroDatasets: e.g. these two files are different but shouldnt.

https://github.com/OpenNeuroDatasets/ds004078/blob/main/sub-01/meg/sub-01_task-RDR_run-1_events.tsv
https://openneuro.org/datasets/ds004078/versions/1.0.3/file-display/sub-01:meg:sub-01_task-RDR_run-1_events.tsv

### Operating system

The issue is on the server side

**Comment by adswa** [comment]
Hi, and thanks for raising this! It looks like an update from OpenNeuro was not pushed to GitHub, an the two most recent versions of that dataset are missing. The best place for this issue is https://github.com/OpenNeuroOrg/openneuro/issues, and I've taken the liberty to link it to https://github.com/OpenNeuroOrg/openneuro/issues/1743#issuecomment-1266868789, an issue which seems to track a range of datasets with missing updates. 
I'll close this issue here and hope for updates on OpenNeuro's end, but feel free to reopen or ping in another issue if anything else is wrong.
