### ISSUE TITLE
[BUG] handbook renders page titles strangely

### ISSUE THREAD

**Issue by asmacdo** [datalad-handbook/book#884]
### Current behavior

Subpages such as http://handbook.datalad.org/en/latest/intro/narrative.html and the pictured nesting page do something funny

![20221213_093159_9022251014833408132_20221213093524(1)](https://user-images.githubusercontent.com/1028657/207362826-91e66b2e-1c7c-4d91-8446-7374236760a7.jpg)

### Operating system

- Linux (F35)

### Browser

- Firefox

**Comment by adswa** [comment]
hey @all-contributors please add @asmacdo for bug

**Comment by adswa** [comment]
ping https://github.com/datalad-handbook/book/issues/379

**Comment by adswa** [comment]
The issue has been present for quite a while, and after staring at this for two hours, and reanalyzing everything from scratch, I realized that I did all of that two years ago already and even filed a [bug report](https://github.com/sphinx-doc/sphinx/issues/7104) that identified the issue as 'not a bug'. Thanks for nothing, long-term memory.

Anyway, the reason for this issue is that the ``{{ title }}`` placeholder in [layout.html](https://github.com/datalad-handbook/book/blob/main/docs/_templates/layout.html) exposes the 'section-number' individually in ``span`` element due to https://github.com/sphinx-doc/sphinx/issues/6613
![image](https://user-images.githubusercontent.com/29738718/209292149-b4819a18-70e7-4367-87af-cfa841fb8a54.png)
When this placeholder is used in a meta tag (``content="{{ title }} {{ titlesuffix }}"``) things break and expand incorrectly:

![image](https://user-images.githubusercontent.com/29738718/209292447-f6cbd7ee-47ad-454e-a8a8-206bba9ce167.png)

And the rendered HTML messes this up even more by splitting this across ``header`` and ``body`` of the page, such that the actual title ends up as a random string right at the start of the body.

![image](https://user-images.githubusercontent.com/29738718/209293080-767eb277-697c-4a0b-8b2a-38a745003d0d.png)

My thoughts are:
* I don't understand web development enough to appreciate or understand the importance of metadata tags. However, as it currently stands, this metadata tag is simply broken, containing no useful information for whatever process or agent would be interested in it.
* There are more bugs in this than the rendering issue, because I don't think that all the metadata tags that come after the title are supposed to be in the body.
* The layout is one of the few leftovers from the sphinx project we forked to create the starting state of the handbook, and was introduced there as social card support: https://github.com/realpython/python-guide/commit/a550d579d6b59016c916df49d47ea63baf9d5058. That project does not face the same issue because they don't have section numbers. For us, though, section numbers are imperative to get correspondence between the HTML and PDF rendering of the book. And because the metadata is all garbled, the social card functionality is actually garbled, too:

![image](https://user-images.githubusercontent.com/29738718/209300164-d061f3c0-a3ea-4b94-bfa7-3355f17aefaf.png)

* My verdict would be to get rid of that meta tag entirely. It was introduced as social card support so I suspect its not  a tag any process searches for by default, and I'm fine with limiting the metadata in the social card in exchange for actually working rendering of social cards and HTML views.
