### ISSUE TITLE
Update catalog chapter based on new release

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#934]
https://github.com/datalad/datalad-catalog/issues/250

**Comment by adswa** [comment]
hi @jsheunis! In our new RFD work experiment, I see you're budgeted with 2 hours for the DataLad-Handbook for the month of May. Thanks for helping out! 

Can I ask you to spend your chunk of time on this issue, since you know best what needs updating? This work isn't 100% dependent on there actually being a 1.0.0 release of the catalog, it can also simply become a branch or draft PR that includes the changes you already know about. 

I'm trying to anticipate questions, but I only so far came up with one:
-  If there is a breaking change that would render a documented command non-cross-compatible between versions, my suggestion would be to add a version note requiring v1.0.0 at the top of the page and remove everything related to lower versions that would not work with the version. Infos about past versions could be assessed by readers in a previous handbook version, e.g., 0.17.0

If there are other questions or comments you may have, just leave them as a comment to this issue :) 
Let me know if this would work for you, or if I should find something else. Thanks! :raised_hands: :)

**Comment by jsheunis** [comment]
Sounds good to me, thanks for the ping!

> If there is a breaking change that would render a documented command non-cross-compatible between versions, my suggestion would be to add a version note requiring v1.0.0 at the top of the page and remove everything related to lower versions that would not work with the version. Infos about past versions could be assessed by readers in a previous handbook version, e.g., 0.17.0

Will do this 👍

**Comment by jsheunis** [comment]
@adswa do you maybe have an example where it's indicated that a specific version of a package is required for specific runrecords? I'm not sure what syntax to use for this.

**Comment by adswa** [comment]
In the past I have simply done this with an RST adminition (I believe ``.. importantnote::``), with a free-text note that the following chapter/section/function/parameter needs at least version XY. I think the most elegant way would be to include a statement in the section introduction that this walkthrough is based on catalog versions XY and higher.

**Comment by jsheunis** [comment]
Ah ok thanks, I mistakenly interpreted that there was a mechanism to include a RST metadata that actually uses a specified version for the runrecords :)
